### ISSUE TITLE
Database connection closes unexpectedly

### ISSUE THREAD

**Issue by alexbagirov** [MoarCatz/nmaps-telegram#44]
Here's what I usually see in the logs:
```
[06-04 15:34:17] [ERROR] [bot] 
Apr 06 20:34:18 nmaps app/worker.1:  An uncaught error was raised while processing the update 
Apr 06 20:34:18 nmaps app/worker.1:  Traceback (most recent call last): 
Apr 06 20:34:18 nmaps app/worker.1:    File "/app/.heroku/python/lib/python3.6/site-packages/telegram/ext/dispatcher.py", line 279, in process_update 
Apr 06 20:34:18 nmaps app/worker.1:      handler.handle_update(update, self) 
Apr 06 20:34:18 nmaps app/worker.1:    File "/app/.heroku/python/lib/python3.6/site-packages/telegram/ext/conversationhandler.py", line 305, in handle_update 
Apr 06 20:34:18 nmaps app/worker.1:      new_state = self.current_handler.handle_update(update, dispatcher) 
Apr 06 20:34:18 nmaps app/worker.1:    File "/app/.heroku/python/lib/python3.6/site-packages/telegram/ext/regexhandler.py", line 173, in handle_update 
Apr 06 20:34:18 nmaps app/worker.1:      return self.callback(dispatcher.bot, update, **optional_args) 
Apr 06 20:34:18 nmaps app/worker.1:    File "bot.py", line 36, in wrapped_private 
Apr 06 20:34:18 nmaps app/worker.1:      return f(bot, update, *args, **kwargs) 
Apr 06 20:34:18 nmaps app/worker.1:    File "bot.py", line 221, in cancel 
Apr 06 20:34:18 nmaps app/worker.1:      subscribed(update.message.from_user.id))) 
Apr 06 20:34:18 nmaps app/worker.1:    File "/app/subscription.py", line 24, in subscribed 
Apr 06 20:34:18 nmaps app/worker.1:      c = db.cursor() 
Apr 06 20:34:18 nmaps app/worker.1:  psycopg2.InterfaceError: connection already closed 
```

We should add some checks.

**Comment by alexbagirov** [comment]
Something like [that](https://stackoverflow.com/questions/35651586/psycopg2-cursor-already-closed) should be helpful.
```
try:
        cursor.execute(query)
    except Exception as e:
        print e.message
        conn = psycopg2.connect(....)
        cursor = conn.cursor()
```
