### ISSUE TITLE
Group chat user lookup error

### ISSUE THREAD

**Issue by alexbagirov** [MoarCatz/nmaps-telegram#57]
```
Feb 20 13:57:24 nmaps app/worker.1:  An uncaught error was raised while processing the update 
Feb 20 13:57:24 nmaps app/worker.1:  Traceback (most recent call last): 
Feb 20 13:57:24 nmaps app/worker.1:    File "/app/.heroku/python/lib/python3.6/site-packages/telegram/ext/dispatcher.py", line 279, in process_update 
Feb 20 13:57:24 nmaps app/worker.1:      handler.handle_update(update, self) 
Feb 20 13:57:24 nmaps app/worker.1:    File "/app/.heroku/python/lib/python3.6/site-packages/telegram/ext/messagehandler.py", line 169, in handle_update 
Feb 20 13:57:24 nmaps app/worker.1:      return self.callback(dispatcher.bot, update, **optional_args) 
Feb 20 13:57:24 nmaps app/worker.1:    File "/app/features/hashtag.py", line 24, in hashtag 
Feb 20 13:57:24 nmaps app/worker.1:      tags[entity](bot, extract_reply(message)) 
Feb 20 13:57:24 nmaps app/worker.1:    File "/app/features/roads.py", line 53, in new_roadblock 
Feb 20 13:57:24 nmaps app/worker.1:      if banned(message.from_user) or message.chat_id == roads_chat \ 
Feb 20 13:57:24 nmaps app/worker.1:    File "<string>", line 2, in banned 
Feb 20 13:57:24 nmaps app/worker.1:    File "/app/.heroku/python/lib/python3.6/site-packages/pony/orm/core.py", line 528, in new_func 
Feb 20 13:57:24 nmaps app/worker.1:      result = func(*args, **kwargs) 
Feb 20 13:57:24 nmaps app/worker.1:    File "/app/features/roads.py", line 198, in banned 
Feb 20 13:57:24 nmaps app/worker.1:      return U.get(user_id=user.id).is_banned() 
Feb 20 13:57:24 nmaps app/worker.1:  AttributeError: 'NoneType' object has no attribute 'is_banned'

**Comment by alexbagirov** [comment]
Fixed in 5b8ae12c9efba760db02f54a1b4819fc945b3248
